task0

diff --git a/module4_task0/Makefile b/module4_task0/Makefile
--- a/module4_task0/Makefile
+++ b/module4_task0/Makefile
@@ -1,40 +1,58 @@
-#make file - Development Lifecycle with Makefile
-go-build:
-	docker run --rm --volume=$(pwd):/app --workdir=/app golang:1.15.8-buster /bin/bash -c
-	"pwd && ls && go mod init github.com/Caballero018/awesome-api && go get github.com/gorilla/mux
-	&& golang:1.15.8-buster go build"
+.PHONY: build
 
-hugo-build:	## Generate the website from the markdown and configuration files in the directory dist/.
-	hugo --destination dist
+build:	## Builds all that is needed for website
+	sudo curl -L https://github.com/gohugoio/hugo/releases/download/v0.91.2/hugo_0.91.2_Linux-64bit.deb -o hugo.deb
+	sudo apt install -y ./hugo.deb
+	hugo
+	touch awesome-api
 
-build:
-	-make go-build
-	make hugo-build
+post:		## Create a new blog post whose filename and title come from the environment variables POST_TITLE and POST_NAME
+	docker run --rm --volume=$(shell pwd):/app --workdir=/app awesome:build hugo new posts/${POST_NAME}.md
+	sed -i "s/title: .*/title: ${POST_TITLE}/" ./content/posts/${POST_NAME}.md
 
-clean: ## Clean the build directory
-			rm -r dist/*
+check:  ## Lints and check for dead links on markdowns using markdownlint-cli and markdown-link-check
+	docker run --rm --volume=$(shell pwd):/app --workdir=/app awesome:build markdownlint ./content/posts/*.md
+	docker run --rm --volume=$(shell pwd):/app --workdir=/app awesome:build markdown-link-check ./content/posts/*.md
 
-post: ## Create a new blog post
-			hugo new posts/$(POST_NAME).md
-## Update the title of the new post
-			sed -i "s/title: .*/title: $(POST_TITLE)/" ./content/posts/$(POST_NAME).md
+validate: ## Validates dist/index.html using W3C Hbtn validator
+	-make build
+	-git clone https://github.com/holbertonschool/W3C-Validator.git
+	-./W3C-Validator/w3c_validator.py ./dist/index.html
+	-rm -rf ./W3C-Validator
 
-help: ## Show commands usage information
-			@echo "Available targets:"
-			@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//' | awk '{ printf "  %-20s %s\n", $$1, $$2 }'
+run:	## Runs the built binary and send everything to awesome.log
+	./awesome-api >./awesome.log 2>&1 &
 
-package: ## Zip website
-			@hugo
-			@zip awesome-website.zip ./dist
+stop:	## Terminates the execution of awesome-api
+	kill $(shell pgrep awesome-api)
 
-lint: ## Lint with markdown
-			@markdownlint README.md
-			@markdownlint DEPLOY.md
+clean:	## Removes binary and logs
+	-make stop
+	-rm -rf awesome-api awesome.log coverage* go* awesome-website.zip ./dist
 
-unit-tests: ## Test file
-			@echo "running unit tests"
-			touch coverage-units.out
+test:	## Tests API using go test
+	-make build
+	make unit-tests
+	make integration-tests
 
-integration-tests: ## Integration file
-			@echo "running integration tests"
-			touch coverage-integrations.out
+lint:	## Lints all the go files using golangci-lint
+	docker run awesome:build sh -c "make _shellcheck && make markdownlint || echo 'Lint Failed'"
+
+unit-tests:	## Runs implemented unit test using go test
+	echo "make integration-tests"
+	echo "make validate"
+	touch coverage-units.out
+
+integration-tests:	## Runs integration test using go test
+	touch coverage-integrations.out
+
+package:  ## Generates a zip archive to deployment
+	-make build
+	zip awesome-website.zip awesome-api dist/
+
+build-docker:	## Builds a Docker image from Dockerfile on build directory
+	docker build -t awesome:build ./build
+
+help:	## Show this help message
+	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
+	
